
services:
  database:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: database
    hostname: root
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manager
  server:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: server
    command: ./api-server
    ports:
      - "8080:8080"
    depends_on:
      - database

# command ===========
# docker-compose up